name: Deploy to VPS

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 83.228.207.79
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "🚀 Déploiement de digiflow-agency.fr..."
          
          # Variables FIXES pour ce site
          PROJECT_DIR="/var/www/apps/digiflow-agency.fr"
          APP_NAME="digiflow-agency-fr"
          
          # Vérifier que le dossier existe
          if [ ! -d "$PROJECT_DIR" ]; then
            echo "❌ Dossier non trouvé: $PROJECT_DIR"
            exit 1
          fi
          
          cd "$PROJECT_DIR"
          
          # Vérifier que c'est un repo git
          if [ ! -d ".git" ]; then
            echo "❌ Pas un repository git"
            exit 1
          fi
          
          # Sauvegarder les changements locaux
          git stash push -m "auto-deploy-$(date +%Y%m%d-%H%M%S)" --include-untracked || true
          
          # Récupérer les derniers changements
          git fetch origin
          
          # Reset sur la branche principale
          if git show-ref --verify --quiet refs/remotes/origin/main; then
            git reset --hard origin/main
          elif git show-ref --verify --quiet refs/remotes/origin/master; then
            git reset --hard origin/master
          else
            echo "❌ Aucune branche main/master trouvée"
            exit 1
          fi
          
          # Installer les dépendances
          if [ -f "pnpm-lock.yaml" ]; then
            echo "📦 Installation avec pnpm..."
            pnpm install --frozen-lockfile
          elif [ -f "package-lock.json" ]; then
            echo "📦 Installation avec npm ci..."
            npm ci
          elif [ -f "yarn.lock" ]; then
            echo "📦 Installation avec yarn..."
            yarn install --frozen-lockfile
          else
            echo "📦 Installation avec npm..."
            npm install
          fi
          
          # Build si nécessaire
          if grep -q '"build"' package.json; then
            echo "🔨 Build de production..."
            if [ -f "pnpm-lock.yaml" ]; then
              pnpm build
            elif [ -f "yarn.lock" ]; then
              yarn build
            else
              npm run build
            fi
          fi
          
          # Redémarrer PM2
          echo "🔄 Redémarrage de l'application PM2..."
          if pm2 describe "$APP_NAME" > /dev/null 2>&1; then
            pm2 restart "$APP_NAME"
            echo "✅ Application redémarrée"
          else
            echo "⚠️ Application PM2 non trouvée, tentative avec le script de déploiement..."
            # Utiliser le script de déploiement s'il existe
            DEPLOY_SCRIPT="/home/ubuntu/deploy-$APP_NAME.sh"
            if [ -f "$DEPLOY_SCRIPT" ]; then
              bash "$DEPLOY_SCRIPT"
            else
              echo "❌ Aucun script de déploiement trouvé"
              exit 1
            fi
          fi
          
          echo "✅ Déploiement terminé pour digiflow-agency.fr!"
          pm2 status "$APP_NAME"
