name: Deploy to VPS

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 83.228.207.79
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "🚀 Déploiement de ${{ secrets.DOMAIN }}..."
          
          PROJECT_DIR="/var/www/apps/${{ secrets.DOMAIN }}"
          APP_NAME="$(echo ${{ secrets.DOMAIN }} | sed 's/\./-/g')"
          
          cd "$PROJECT_DIR"
          
          # TOUJOURS sauvegarder et forcer la mise à jour
          git stash push -m "auto-deploy-$(date +%Y%m%d-%H%M%S)" --include-untracked
          git fetch origin
          git reset --hard origin/main || git reset --hard origin/master
          
          # Installer les dépendances
          if [ -f "pnpm-lock.yaml" ]; then
            pnpm install --frozen-lockfile
          elif [ -f "package-lock.json" ]; then
            npm ci
          else
            npm install
          fi
          
          # Build si nécessaire
          if grep -q '"build"' package.json; then
            pnpm build || npm run build
          fi
          
          # Redémarrer PM2
          pm2 restart "$APP_NAME" || echo "App non trouvée"
          
          echo "✅ Déploiement terminé!"
